version: '3.1'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 6060:8080
  db:
    image: postgres:10
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: restaurantdb