version: '3.1'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 6060:8080
  db:
    image: postgres:10
    restart: always
    ports:
        - 5432:5432
    volumes:
        - ./setup-db.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: restaurantdb